//
//  File.swift
//  
//
//  Created by Siddhant Mehta on 2023-12-18.
//

import SwiftUI

public enum Palettes {
    public struct amber: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.amber._1, dark: StaticColor.amberDark._1)
        public static let _2 = Color(light: StaticColor.amber._2, dark: StaticColor.amberDark._2)
        public static let _3 = Color(light: StaticColor.amber._3, dark: StaticColor.amberDark._3)
        public static let _4 = Color(light: StaticColor.amber._4, dark: StaticColor.amberDark._4)
        public static let _5 = Color(light: StaticColor.amber._5, dark: StaticColor.amberDark._5)
        public static let _6 = Color(light: StaticColor.amber._6, dark: StaticColor.amberDark._6)
        public static let _7 = Color(light: StaticColor.amber._7, dark: StaticColor.amberDark._7)
        public static let _8 = Color(light: StaticColor.amber._8, dark: StaticColor.amberDark._8)
        public static let _9 = Color(light: StaticColor.amber._9, dark: StaticColor.amberDark._9)
        public static let _10 = Color(light: StaticColor.amber._10, dark: StaticColor.amberDark._10)
        public static let _11 = Color(light: StaticColor.amber._11, dark: StaticColor.amberDark._11)
        public static let _12 = Color(light: StaticColor.amber._12, dark: StaticColor.amberDark._12)
        public static let _1Alpha = Color(light: StaticColor.amberAlpha._1, dark: StaticColor.amberDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.amberAlpha._2, dark: StaticColor.amberDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.amberAlpha._3, dark: StaticColor.amberDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.amberAlpha._4, dark: StaticColor.amberDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.amberAlpha._5, dark: StaticColor.amberDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.amberAlpha._6, dark: StaticColor.amberDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.amberAlpha._7, dark: StaticColor.amberDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.amberAlpha._8, dark: StaticColor.amberDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.amberAlpha._9, dark: StaticColor.amberDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.amberAlpha._10, dark: StaticColor.amberDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.amberAlpha._11, dark: StaticColor.amberDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.amberAlpha._12, dark: StaticColor.amberDarkAlpha._12)
    }
    public struct blackAlpha: PaletteColor {
        public init() {}
        public static let _1 = StaticColor.blackAlpha._1
        public static let _2 = StaticColor.blackAlpha._2
        public static let _3 = StaticColor.blackAlpha._3
        public static let _4 = StaticColor.blackAlpha._4
        public static let _5 = StaticColor.blackAlpha._5
        public static let _6 = StaticColor.blackAlpha._6
        public static let _7 = StaticColor.blackAlpha._7
        public static let _8 = StaticColor.blackAlpha._8
        public static let _9 = StaticColor.blackAlpha._9
        public static let _10 = StaticColor.blackAlpha._10
        public static let _11 = StaticColor.blackAlpha._11
        public static let _12 = StaticColor.blackAlpha._12
        public static let _1Alpha = StaticColor.blackAlpha._1
        public static let _2Alpha = StaticColor.blackAlpha._2
        public static let _3Alpha = StaticColor.blackAlpha._3
        public static let _4Alpha = StaticColor.blackAlpha._4
        public static let _5Alpha = StaticColor.blackAlpha._5
        public static let _6Alpha = StaticColor.blackAlpha._6
        public static let _7Alpha = StaticColor.blackAlpha._7
        public static let _8Alpha = StaticColor.blackAlpha._8
        public static let _9Alpha = StaticColor.blackAlpha._9
        public static let _10Alpha = StaticColor.blackAlpha._10
        public static let _11Alpha = StaticColor.blackAlpha._11
        public static let _12Alpha = StaticColor.blackAlpha._12
    }
    public struct blue: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.blue._1, dark: StaticColor.blueDark._1)
        public static let _2 = Color(light: StaticColor.blue._2, dark: StaticColor.blueDark._2)
        public static let _3 = Color(light: StaticColor.blue._3, dark: StaticColor.blueDark._3)
        public static let _4 = Color(light: StaticColor.blue._4, dark: StaticColor.blueDark._4)
        public static let _5 = Color(light: StaticColor.blue._5, dark: StaticColor.blueDark._5)
        public static let _6 = Color(light: StaticColor.blue._6, dark: StaticColor.blueDark._6)
        public static let _7 = Color(light: StaticColor.blue._7, dark: StaticColor.blueDark._7)
        public static let _8 = Color(light: StaticColor.blue._8, dark: StaticColor.blueDark._8)
        public static let _9 = Color(light: StaticColor.blue._9, dark: StaticColor.blueDark._9)
        public static let _10 = Color(light: StaticColor.blue._10, dark: StaticColor.blueDark._10)
        public static let _11 = Color(light: StaticColor.blue._11, dark: StaticColor.blueDark._11)
        public static let _12 = Color(light: StaticColor.blue._12, dark: StaticColor.blueDark._12)
        public static let _1Alpha = Color(light: StaticColor.blueAlpha._1, dark: StaticColor.blueDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.blueAlpha._2, dark: StaticColor.blueDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.blueAlpha._3, dark: StaticColor.blueDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.blueAlpha._4, dark: StaticColor.blueDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.blueAlpha._5, dark: StaticColor.blueDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.blueAlpha._6, dark: StaticColor.blueDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.blueAlpha._7, dark: StaticColor.blueDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.blueAlpha._8, dark: StaticColor.blueDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.blueAlpha._9, dark: StaticColor.blueDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.blueAlpha._10, dark: StaticColor.blueDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.blueAlpha._11, dark: StaticColor.blueDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.blueAlpha._12, dark: StaticColor.blueDarkAlpha._12)
    }
    public struct bronze: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.bronze._1, dark: StaticColor.bronzeDark._1)
        public static let _2 = Color(light: StaticColor.bronze._2, dark: StaticColor.bronzeDark._2)
        public static let _3 = Color(light: StaticColor.bronze._3, dark: StaticColor.bronzeDark._3)
        public static let _4 = Color(light: StaticColor.bronze._4, dark: StaticColor.bronzeDark._4)
        public static let _5 = Color(light: StaticColor.bronze._5, dark: StaticColor.bronzeDark._5)
        public static let _6 = Color(light: StaticColor.bronze._6, dark: StaticColor.bronzeDark._6)
        public static let _7 = Color(light: StaticColor.bronze._7, dark: StaticColor.bronzeDark._7)
        public static let _8 = Color(light: StaticColor.bronze._8, dark: StaticColor.bronzeDark._8)
        public static let _9 = Color(light: StaticColor.bronze._9, dark: StaticColor.bronzeDark._9)
        public static let _10 = Color(light: StaticColor.bronze._10, dark: StaticColor.bronzeDark._10)
        public static let _11 = Color(light: StaticColor.bronze._11, dark: StaticColor.bronzeDark._11)
        public static let _12 = Color(light: StaticColor.bronze._12, dark: StaticColor.bronzeDark._12)
        public static let _1Alpha = Color(light: StaticColor.bronzeAlpha._1, dark: StaticColor.bronzeDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.bronzeAlpha._2, dark: StaticColor.bronzeDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.bronzeAlpha._3, dark: StaticColor.bronzeDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.bronzeAlpha._4, dark: StaticColor.bronzeDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.bronzeAlpha._5, dark: StaticColor.bronzeDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.bronzeAlpha._6, dark: StaticColor.bronzeDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.bronzeAlpha._7, dark: StaticColor.bronzeDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.bronzeAlpha._8, dark: StaticColor.bronzeDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.bronzeAlpha._9, dark: StaticColor.bronzeDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.bronzeAlpha._10, dark: StaticColor.bronzeDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.bronzeAlpha._11, dark: StaticColor.bronzeDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.bronzeAlpha._12, dark: StaticColor.bronzeDarkAlpha._12)
    }
    public struct brown: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.brown._1, dark: StaticColor.brownDark._1)
        public static let _2 = Color(light: StaticColor.brown._2, dark: StaticColor.brownDark._2)
        public static let _3 = Color(light: StaticColor.brown._3, dark: StaticColor.brownDark._3)
        public static let _4 = Color(light: StaticColor.brown._4, dark: StaticColor.brownDark._4)
        public static let _5 = Color(light: StaticColor.brown._5, dark: StaticColor.brownDark._5)
        public static let _6 = Color(light: StaticColor.brown._6, dark: StaticColor.brownDark._6)
        public static let _7 = Color(light: StaticColor.brown._7, dark: StaticColor.brownDark._7)
        public static let _8 = Color(light: StaticColor.brown._8, dark: StaticColor.brownDark._8)
        public static let _9 = Color(light: StaticColor.brown._9, dark: StaticColor.brownDark._9)
        public static let _10 = Color(light: StaticColor.brown._10, dark: StaticColor.brownDark._10)
        public static let _11 = Color(light: StaticColor.brown._11, dark: StaticColor.brownDark._11)
        public static let _12 = Color(light: StaticColor.brown._12, dark: StaticColor.brownDark._12)
        public static let _1Alpha = Color(light: StaticColor.brownAlpha._1, dark: StaticColor.brownDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.brownAlpha._2, dark: StaticColor.brownDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.brownAlpha._3, dark: StaticColor.brownDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.brownAlpha._4, dark: StaticColor.brownDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.brownAlpha._5, dark: StaticColor.brownDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.brownAlpha._6, dark: StaticColor.brownDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.brownAlpha._7, dark: StaticColor.brownDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.brownAlpha._8, dark: StaticColor.brownDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.brownAlpha._9, dark: StaticColor.brownDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.brownAlpha._10, dark: StaticColor.brownDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.brownAlpha._11, dark: StaticColor.brownDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.brownAlpha._12, dark: StaticColor.brownDarkAlpha._12)
    }
    public struct crimson: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.crimson._1, dark: StaticColor.crimsonDark._1)
        public static let _2 = Color(light: StaticColor.crimson._2, dark: StaticColor.crimsonDark._2)
        public static let _3 = Color(light: StaticColor.crimson._3, dark: StaticColor.crimsonDark._3)
        public static let _4 = Color(light: StaticColor.crimson._4, dark: StaticColor.crimsonDark._4)
        public static let _5 = Color(light: StaticColor.crimson._5, dark: StaticColor.crimsonDark._5)
        public static let _6 = Color(light: StaticColor.crimson._6, dark: StaticColor.crimsonDark._6)
        public static let _7 = Color(light: StaticColor.crimson._7, dark: StaticColor.crimsonDark._7)
        public static let _8 = Color(light: StaticColor.crimson._8, dark: StaticColor.crimsonDark._8)
        public static let _9 = Color(light: StaticColor.crimson._9, dark: StaticColor.crimsonDark._9)
        public static let _10 = Color(light: StaticColor.crimson._10, dark: StaticColor.crimsonDark._10)
        public static let _11 = Color(light: StaticColor.crimson._11, dark: StaticColor.crimsonDark._11)
        public static let _12 = Color(light: StaticColor.crimson._12, dark: StaticColor.crimsonDark._12)
        public static let _1Alpha = Color(light: StaticColor.crimsonAlpha._1, dark: StaticColor.crimsonDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.crimsonAlpha._2, dark: StaticColor.crimsonDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.crimsonAlpha._3, dark: StaticColor.crimsonDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.crimsonAlpha._4, dark: StaticColor.crimsonDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.crimsonAlpha._5, dark: StaticColor.crimsonDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.crimsonAlpha._6, dark: StaticColor.crimsonDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.crimsonAlpha._7, dark: StaticColor.crimsonDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.crimsonAlpha._8, dark: StaticColor.crimsonDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.crimsonAlpha._9, dark: StaticColor.crimsonDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.crimsonAlpha._10, dark: StaticColor.crimsonDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.crimsonAlpha._11, dark: StaticColor.crimsonDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.crimsonAlpha._12, dark: StaticColor.crimsonDarkAlpha._12)
    }
    public struct cyan: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.cyan._1, dark: StaticColor.cyanDark._1)
        public static let _2 = Color(light: StaticColor.cyan._2, dark: StaticColor.cyanDark._2)
        public static let _3 = Color(light: StaticColor.cyan._3, dark: StaticColor.cyanDark._3)
        public static let _4 = Color(light: StaticColor.cyan._4, dark: StaticColor.cyanDark._4)
        public static let _5 = Color(light: StaticColor.cyan._5, dark: StaticColor.cyanDark._5)
        public static let _6 = Color(light: StaticColor.cyan._6, dark: StaticColor.cyanDark._6)
        public static let _7 = Color(light: StaticColor.cyan._7, dark: StaticColor.cyanDark._7)
        public static let _8 = Color(light: StaticColor.cyan._8, dark: StaticColor.cyanDark._8)
        public static let _9 = Color(light: StaticColor.cyan._9, dark: StaticColor.cyanDark._9)
        public static let _10 = Color(light: StaticColor.cyan._10, dark: StaticColor.cyanDark._10)
        public static let _11 = Color(light: StaticColor.cyan._11, dark: StaticColor.cyanDark._11)
        public static let _12 = Color(light: StaticColor.cyan._12, dark: StaticColor.cyanDark._12)
        public static let _1Alpha = Color(light: StaticColor.cyanAlpha._1, dark: StaticColor.cyanDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.cyanAlpha._2, dark: StaticColor.cyanDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.cyanAlpha._3, dark: StaticColor.cyanDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.cyanAlpha._4, dark: StaticColor.cyanDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.cyanAlpha._5, dark: StaticColor.cyanDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.cyanAlpha._6, dark: StaticColor.cyanDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.cyanAlpha._7, dark: StaticColor.cyanDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.cyanAlpha._8, dark: StaticColor.cyanDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.cyanAlpha._9, dark: StaticColor.cyanDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.cyanAlpha._10, dark: StaticColor.cyanDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.cyanAlpha._11, dark: StaticColor.cyanDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.cyanAlpha._12, dark: StaticColor.cyanDarkAlpha._12)
    }
    public struct gold: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.gold._1, dark: StaticColor.goldDark._1)
        public static let _2 = Color(light: StaticColor.gold._2, dark: StaticColor.goldDark._2)
        public static let _3 = Color(light: StaticColor.gold._3, dark: StaticColor.goldDark._3)
        public static let _4 = Color(light: StaticColor.gold._4, dark: StaticColor.goldDark._4)
        public static let _5 = Color(light: StaticColor.gold._5, dark: StaticColor.goldDark._5)
        public static let _6 = Color(light: StaticColor.gold._6, dark: StaticColor.goldDark._6)
        public static let _7 = Color(light: StaticColor.gold._7, dark: StaticColor.goldDark._7)
        public static let _8 = Color(light: StaticColor.gold._8, dark: StaticColor.goldDark._8)
        public static let _9 = Color(light: StaticColor.gold._9, dark: StaticColor.goldDark._9)
        public static let _10 = Color(light: StaticColor.gold._10, dark: StaticColor.goldDark._10)
        public static let _11 = Color(light: StaticColor.gold._11, dark: StaticColor.goldDark._11)
        public static let _12 = Color(light: StaticColor.gold._12, dark: StaticColor.goldDark._12)
        public static let _1Alpha = Color(light: StaticColor.goldAlpha._1, dark: StaticColor.goldDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.goldAlpha._2, dark: StaticColor.goldDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.goldAlpha._3, dark: StaticColor.goldDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.goldAlpha._4, dark: StaticColor.goldDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.goldAlpha._5, dark: StaticColor.goldDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.goldAlpha._6, dark: StaticColor.goldDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.goldAlpha._7, dark: StaticColor.goldDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.goldAlpha._8, dark: StaticColor.goldDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.goldAlpha._9, dark: StaticColor.goldDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.goldAlpha._10, dark: StaticColor.goldDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.goldAlpha._11, dark: StaticColor.goldDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.goldAlpha._12, dark: StaticColor.goldDarkAlpha._12)
    }
    public struct grass: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.grass._1, dark: StaticColor.grassDark._1)
        public static let _2 = Color(light: StaticColor.grass._2, dark: StaticColor.grassDark._2)
        public static let _3 = Color(light: StaticColor.grass._3, dark: StaticColor.grassDark._3)
        public static let _4 = Color(light: StaticColor.grass._4, dark: StaticColor.grassDark._4)
        public static let _5 = Color(light: StaticColor.grass._5, dark: StaticColor.grassDark._5)
        public static let _6 = Color(light: StaticColor.grass._6, dark: StaticColor.grassDark._6)
        public static let _7 = Color(light: StaticColor.grass._7, dark: StaticColor.grassDark._7)
        public static let _8 = Color(light: StaticColor.grass._8, dark: StaticColor.grassDark._8)
        public static let _9 = Color(light: StaticColor.grass._9, dark: StaticColor.grassDark._9)
        public static let _10 = Color(light: StaticColor.grass._10, dark: StaticColor.grassDark._10)
        public static let _11 = Color(light: StaticColor.grass._11, dark: StaticColor.grassDark._11)
        public static let _12 = Color(light: StaticColor.grass._12, dark: StaticColor.grassDark._12)
        public static let _1Alpha = Color(light: StaticColor.grassAlpha._1, dark: StaticColor.grassDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.grassAlpha._2, dark: StaticColor.grassDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.grassAlpha._3, dark: StaticColor.grassDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.grassAlpha._4, dark: StaticColor.grassDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.grassAlpha._5, dark: StaticColor.grassDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.grassAlpha._6, dark: StaticColor.grassDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.grassAlpha._7, dark: StaticColor.grassDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.grassAlpha._8, dark: StaticColor.grassDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.grassAlpha._9, dark: StaticColor.grassDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.grassAlpha._10, dark: StaticColor.grassDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.grassAlpha._11, dark: StaticColor.grassDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.grassAlpha._12, dark: StaticColor.grassDarkAlpha._12)
    }
    public struct gray: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.gray._1, dark: StaticColor.grayDark._1)
        public static let _2 = Color(light: StaticColor.gray._2, dark: StaticColor.grayDark._2)
        public static let _3 = Color(light: StaticColor.gray._3, dark: StaticColor.grayDark._3)
        public static let _4 = Color(light: StaticColor.gray._4, dark: StaticColor.grayDark._4)
        public static let _5 = Color(light: StaticColor.gray._5, dark: StaticColor.grayDark._5)
        public static let _6 = Color(light: StaticColor.gray._6, dark: StaticColor.grayDark._6)
        public static let _7 = Color(light: StaticColor.gray._7, dark: StaticColor.grayDark._7)
        public static let _8 = Color(light: StaticColor.gray._8, dark: StaticColor.grayDark._8)
        public static let _9 = Color(light: StaticColor.gray._9, dark: StaticColor.grayDark._9)
        public static let _10 = Color(light: StaticColor.gray._10, dark: StaticColor.grayDark._10)
        public static let _11 = Color(light: StaticColor.gray._11, dark: StaticColor.grayDark._11)
        public static let _12 = Color(light: StaticColor.gray._12, dark: StaticColor.grayDark._12)
        public static let _1Alpha = Color(light: StaticColor.grayAlpha._1, dark: StaticColor.grayDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.grayAlpha._2, dark: StaticColor.grayDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.grayAlpha._3, dark: StaticColor.grayDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.grayAlpha._4, dark: StaticColor.grayDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.grayAlpha._5, dark: StaticColor.grayDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.grayAlpha._6, dark: StaticColor.grayDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.grayAlpha._7, dark: StaticColor.grayDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.grayAlpha._8, dark: StaticColor.grayDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.grayAlpha._9, dark: StaticColor.grayDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.grayAlpha._10, dark: StaticColor.grayDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.grayAlpha._11, dark: StaticColor.grayDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.grayAlpha._12, dark: StaticColor.grayDarkAlpha._12)
    }
    public struct green: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.green._1, dark: StaticColor.greenDark._1)
        public static let _2 = Color(light: StaticColor.green._2, dark: StaticColor.greenDark._2)
        public static let _3 = Color(light: StaticColor.green._3, dark: StaticColor.greenDark._3)
        public static let _4 = Color(light: StaticColor.green._4, dark: StaticColor.greenDark._4)
        public static let _5 = Color(light: StaticColor.green._5, dark: StaticColor.greenDark._5)
        public static let _6 = Color(light: StaticColor.green._6, dark: StaticColor.greenDark._6)
        public static let _7 = Color(light: StaticColor.green._7, dark: StaticColor.greenDark._7)
        public static let _8 = Color(light: StaticColor.green._8, dark: StaticColor.greenDark._8)
        public static let _9 = Color(light: StaticColor.green._9, dark: StaticColor.greenDark._9)
        public static let _10 = Color(light: StaticColor.green._10, dark: StaticColor.greenDark._10)
        public static let _11 = Color(light: StaticColor.green._11, dark: StaticColor.greenDark._11)
        public static let _12 = Color(light: StaticColor.green._12, dark: StaticColor.greenDark._12)
        public static let _1Alpha = Color(light: StaticColor.greenAlpha._1, dark: StaticColor.greenDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.greenAlpha._2, dark: StaticColor.greenDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.greenAlpha._3, dark: StaticColor.greenDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.greenAlpha._4, dark: StaticColor.greenDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.greenAlpha._5, dark: StaticColor.greenDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.greenAlpha._6, dark: StaticColor.greenDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.greenAlpha._7, dark: StaticColor.greenDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.greenAlpha._8, dark: StaticColor.greenDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.greenAlpha._9, dark: StaticColor.greenDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.greenAlpha._10, dark: StaticColor.greenDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.greenAlpha._11, dark: StaticColor.greenDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.greenAlpha._12, dark: StaticColor.greenDarkAlpha._12)
    }
    public struct indigo: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.indigo._1, dark: StaticColor.indigoDark._1)
        public static let _2 = Color(light: StaticColor.indigo._2, dark: StaticColor.indigoDark._2)
        public static let _3 = Color(light: StaticColor.indigo._3, dark: StaticColor.indigoDark._3)
        public static let _4 = Color(light: StaticColor.indigo._4, dark: StaticColor.indigoDark._4)
        public static let _5 = Color(light: StaticColor.indigo._5, dark: StaticColor.indigoDark._5)
        public static let _6 = Color(light: StaticColor.indigo._6, dark: StaticColor.indigoDark._6)
        public static let _7 = Color(light: StaticColor.indigo._7, dark: StaticColor.indigoDark._7)
        public static let _8 = Color(light: StaticColor.indigo._8, dark: StaticColor.indigoDark._8)
        public static let _9 = Color(light: StaticColor.indigo._9, dark: StaticColor.indigoDark._9)
        public static let _10 = Color(light: StaticColor.indigo._10, dark: StaticColor.indigoDark._10)
        public static let _11 = Color(light: StaticColor.indigo._11, dark: StaticColor.indigoDark._11)
        public static let _12 = Color(light: StaticColor.indigo._12, dark: StaticColor.indigoDark._12)
        public static let _1Alpha = Color(light: StaticColor.indigoAlpha._1, dark: StaticColor.indigoDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.indigoAlpha._2, dark: StaticColor.indigoDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.indigoAlpha._3, dark: StaticColor.indigoDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.indigoAlpha._4, dark: StaticColor.indigoDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.indigoAlpha._5, dark: StaticColor.indigoDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.indigoAlpha._6, dark: StaticColor.indigoDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.indigoAlpha._7, dark: StaticColor.indigoDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.indigoAlpha._8, dark: StaticColor.indigoDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.indigoAlpha._9, dark: StaticColor.indigoDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.indigoAlpha._10, dark: StaticColor.indigoDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.indigoAlpha._11, dark: StaticColor.indigoDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.indigoAlpha._12, dark: StaticColor.indigoDarkAlpha._12)
    }
    public struct iris: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.iris._1, dark: StaticColor.irisDark._1)
        public static let _2 = Color(light: StaticColor.iris._2, dark: StaticColor.irisDark._2)
        public static let _3 = Color(light: StaticColor.iris._3, dark: StaticColor.irisDark._3)
        public static let _4 = Color(light: StaticColor.iris._4, dark: StaticColor.irisDark._4)
        public static let _5 = Color(light: StaticColor.iris._5, dark: StaticColor.irisDark._5)
        public static let _6 = Color(light: StaticColor.iris._6, dark: StaticColor.irisDark._6)
        public static let _7 = Color(light: StaticColor.iris._7, dark: StaticColor.irisDark._7)
        public static let _8 = Color(light: StaticColor.iris._8, dark: StaticColor.irisDark._8)
        public static let _9 = Color(light: StaticColor.iris._9, dark: StaticColor.irisDark._9)
        public static let _10 = Color(light: StaticColor.iris._10, dark: StaticColor.irisDark._10)
        public static let _11 = Color(light: StaticColor.iris._11, dark: StaticColor.irisDark._11)
        public static let _12 = Color(light: StaticColor.iris._12, dark: StaticColor.irisDark._12)
        public static let _1Alpha = Color(light: StaticColor.irisAlpha._1, dark: StaticColor.irisDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.irisAlpha._2, dark: StaticColor.irisDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.irisAlpha._3, dark: StaticColor.irisDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.irisAlpha._4, dark: StaticColor.irisDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.irisAlpha._5, dark: StaticColor.irisDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.irisAlpha._6, dark: StaticColor.irisDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.irisAlpha._7, dark: StaticColor.irisDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.irisAlpha._8, dark: StaticColor.irisDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.irisAlpha._9, dark: StaticColor.irisDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.irisAlpha._10, dark: StaticColor.irisDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.irisAlpha._11, dark: StaticColor.irisDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.irisAlpha._12, dark: StaticColor.irisDarkAlpha._12)
    }
    public struct jade: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.jade._1, dark: StaticColor.jadeDark._1)
        public static let _2 = Color(light: StaticColor.jade._2, dark: StaticColor.jadeDark._2)
        public static let _3 = Color(light: StaticColor.jade._3, dark: StaticColor.jadeDark._3)
        public static let _4 = Color(light: StaticColor.jade._4, dark: StaticColor.jadeDark._4)
        public static let _5 = Color(light: StaticColor.jade._5, dark: StaticColor.jadeDark._5)
        public static let _6 = Color(light: StaticColor.jade._6, dark: StaticColor.jadeDark._6)
        public static let _7 = Color(light: StaticColor.jade._7, dark: StaticColor.jadeDark._7)
        public static let _8 = Color(light: StaticColor.jade._8, dark: StaticColor.jadeDark._8)
        public static let _9 = Color(light: StaticColor.jade._9, dark: StaticColor.jadeDark._9)
        public static let _10 = Color(light: StaticColor.jade._10, dark: StaticColor.jadeDark._10)
        public static let _11 = Color(light: StaticColor.jade._11, dark: StaticColor.jadeDark._11)
        public static let _12 = Color(light: StaticColor.jade._12, dark: StaticColor.jadeDark._12)
        public static let _1Alpha = Color(light: StaticColor.jadeAlpha._1, dark: StaticColor.jadeDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.jadeAlpha._2, dark: StaticColor.jadeDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.jadeAlpha._3, dark: StaticColor.jadeDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.jadeAlpha._4, dark: StaticColor.jadeDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.jadeAlpha._5, dark: StaticColor.jadeDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.jadeAlpha._6, dark: StaticColor.jadeDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.jadeAlpha._7, dark: StaticColor.jadeDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.jadeAlpha._8, dark: StaticColor.jadeDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.jadeAlpha._9, dark: StaticColor.jadeDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.jadeAlpha._10, dark: StaticColor.jadeDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.jadeAlpha._11, dark: StaticColor.jadeDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.jadeAlpha._12, dark: StaticColor.jadeDarkAlpha._12)
    }
    public struct lime: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.lime._1, dark: StaticColor.limeDark._1)
        public static let _2 = Color(light: StaticColor.lime._2, dark: StaticColor.limeDark._2)
        public static let _3 = Color(light: StaticColor.lime._3, dark: StaticColor.limeDark._3)
        public static let _4 = Color(light: StaticColor.lime._4, dark: StaticColor.limeDark._4)
        public static let _5 = Color(light: StaticColor.lime._5, dark: StaticColor.limeDark._5)
        public static let _6 = Color(light: StaticColor.lime._6, dark: StaticColor.limeDark._6)
        public static let _7 = Color(light: StaticColor.lime._7, dark: StaticColor.limeDark._7)
        public static let _8 = Color(light: StaticColor.lime._8, dark: StaticColor.limeDark._8)
        public static let _9 = Color(light: StaticColor.lime._9, dark: StaticColor.limeDark._9)
        public static let _10 = Color(light: StaticColor.lime._10, dark: StaticColor.limeDark._10)
        public static let _11 = Color(light: StaticColor.lime._11, dark: StaticColor.limeDark._11)
        public static let _12 = Color(light: StaticColor.lime._12, dark: StaticColor.limeDark._12)
        public static let _1Alpha = Color(light: StaticColor.limeAlpha._1, dark: StaticColor.limeDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.limeAlpha._2, dark: StaticColor.limeDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.limeAlpha._3, dark: StaticColor.limeDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.limeAlpha._4, dark: StaticColor.limeDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.limeAlpha._5, dark: StaticColor.limeDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.limeAlpha._6, dark: StaticColor.limeDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.limeAlpha._7, dark: StaticColor.limeDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.limeAlpha._8, dark: StaticColor.limeDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.limeAlpha._9, dark: StaticColor.limeDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.limeAlpha._10, dark: StaticColor.limeDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.limeAlpha._11, dark: StaticColor.limeDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.limeAlpha._12, dark: StaticColor.limeDarkAlpha._12)
    }
    public struct mauve: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.mauve._1, dark: StaticColor.mauveDark._1)
        public static let _2 = Color(light: StaticColor.mauve._2, dark: StaticColor.mauveDark._2)
        public static let _3 = Color(light: StaticColor.mauve._3, dark: StaticColor.mauveDark._3)
        public static let _4 = Color(light: StaticColor.mauve._4, dark: StaticColor.mauveDark._4)
        public static let _5 = Color(light: StaticColor.mauve._5, dark: StaticColor.mauveDark._5)
        public static let _6 = Color(light: StaticColor.mauve._6, dark: StaticColor.mauveDark._6)
        public static let _7 = Color(light: StaticColor.mauve._7, dark: StaticColor.mauveDark._7)
        public static let _8 = Color(light: StaticColor.mauve._8, dark: StaticColor.mauveDark._8)
        public static let _9 = Color(light: StaticColor.mauve._9, dark: StaticColor.mauveDark._9)
        public static let _10 = Color(light: StaticColor.mauve._10, dark: StaticColor.mauveDark._10)
        public static let _11 = Color(light: StaticColor.mauve._11, dark: StaticColor.mauveDark._11)
        public static let _12 = Color(light: StaticColor.mauve._12, dark: StaticColor.mauveDark._12)
        public static let _1Alpha = Color(light: StaticColor.mauveAlpha._1, dark: StaticColor.mauveDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.mauveAlpha._2, dark: StaticColor.mauveDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.mauveAlpha._3, dark: StaticColor.mauveDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.mauveAlpha._4, dark: StaticColor.mauveDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.mauveAlpha._5, dark: StaticColor.mauveDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.mauveAlpha._6, dark: StaticColor.mauveDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.mauveAlpha._7, dark: StaticColor.mauveDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.mauveAlpha._8, dark: StaticColor.mauveDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.mauveAlpha._9, dark: StaticColor.mauveDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.mauveAlpha._10, dark: StaticColor.mauveDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.mauveAlpha._11, dark: StaticColor.mauveDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.mauveAlpha._12, dark: StaticColor.mauveDarkAlpha._12)
    }
    public struct mint: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.mint._1, dark: StaticColor.mintDark._1)
        public static let _2 = Color(light: StaticColor.mint._2, dark: StaticColor.mintDark._2)
        public static let _3 = Color(light: StaticColor.mint._3, dark: StaticColor.mintDark._3)
        public static let _4 = Color(light: StaticColor.mint._4, dark: StaticColor.mintDark._4)
        public static let _5 = Color(light: StaticColor.mint._5, dark: StaticColor.mintDark._5)
        public static let _6 = Color(light: StaticColor.mint._6, dark: StaticColor.mintDark._6)
        public static let _7 = Color(light: StaticColor.mint._7, dark: StaticColor.mintDark._7)
        public static let _8 = Color(light: StaticColor.mint._8, dark: StaticColor.mintDark._8)
        public static let _9 = Color(light: StaticColor.mint._9, dark: StaticColor.mintDark._9)
        public static let _10 = Color(light: StaticColor.mint._10, dark: StaticColor.mintDark._10)
        public static let _11 = Color(light: StaticColor.mint._11, dark: StaticColor.mintDark._11)
        public static let _12 = Color(light: StaticColor.mint._12, dark: StaticColor.mintDark._12)
        public static let _1Alpha = Color(light: StaticColor.mintAlpha._1, dark: StaticColor.mintDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.mintAlpha._2, dark: StaticColor.mintDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.mintAlpha._3, dark: StaticColor.mintDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.mintAlpha._4, dark: StaticColor.mintDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.mintAlpha._5, dark: StaticColor.mintDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.mintAlpha._6, dark: StaticColor.mintDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.mintAlpha._7, dark: StaticColor.mintDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.mintAlpha._8, dark: StaticColor.mintDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.mintAlpha._9, dark: StaticColor.mintDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.mintAlpha._10, dark: StaticColor.mintDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.mintAlpha._11, dark: StaticColor.mintDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.mintAlpha._12, dark: StaticColor.mintDarkAlpha._12)
    }
    public struct olive: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.olive._1, dark: StaticColor.oliveDark._1)
        public static let _2 = Color(light: StaticColor.olive._2, dark: StaticColor.oliveDark._2)
        public static let _3 = Color(light: StaticColor.olive._3, dark: StaticColor.oliveDark._3)
        public static let _4 = Color(light: StaticColor.olive._4, dark: StaticColor.oliveDark._4)
        public static let _5 = Color(light: StaticColor.olive._5, dark: StaticColor.oliveDark._5)
        public static let _6 = Color(light: StaticColor.olive._6, dark: StaticColor.oliveDark._6)
        public static let _7 = Color(light: StaticColor.olive._7, dark: StaticColor.oliveDark._7)
        public static let _8 = Color(light: StaticColor.olive._8, dark: StaticColor.oliveDark._8)
        public static let _9 = Color(light: StaticColor.olive._9, dark: StaticColor.oliveDark._9)
        public static let _10 = Color(light: StaticColor.olive._10, dark: StaticColor.oliveDark._10)
        public static let _11 = Color(light: StaticColor.olive._11, dark: StaticColor.oliveDark._11)
        public static let _12 = Color(light: StaticColor.olive._12, dark: StaticColor.oliveDark._12)
        public static let _1Alpha = Color(light: StaticColor.oliveAlpha._1, dark: StaticColor.oliveDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.oliveAlpha._2, dark: StaticColor.oliveDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.oliveAlpha._3, dark: StaticColor.oliveDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.oliveAlpha._4, dark: StaticColor.oliveDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.oliveAlpha._5, dark: StaticColor.oliveDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.oliveAlpha._6, dark: StaticColor.oliveDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.oliveAlpha._7, dark: StaticColor.oliveDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.oliveAlpha._8, dark: StaticColor.oliveDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.oliveAlpha._9, dark: StaticColor.oliveDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.oliveAlpha._10, dark: StaticColor.oliveDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.oliveAlpha._11, dark: StaticColor.oliveDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.oliveAlpha._12, dark: StaticColor.oliveDarkAlpha._12)
    }
    public struct orange: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.orange._1, dark: StaticColor.orangeDark._1)
        public static let _2 = Color(light: StaticColor.orange._2, dark: StaticColor.orangeDark._2)
        public static let _3 = Color(light: StaticColor.orange._3, dark: StaticColor.orangeDark._3)
        public static let _4 = Color(light: StaticColor.orange._4, dark: StaticColor.orangeDark._4)
        public static let _5 = Color(light: StaticColor.orange._5, dark: StaticColor.orangeDark._5)
        public static let _6 = Color(light: StaticColor.orange._6, dark: StaticColor.orangeDark._6)
        public static let _7 = Color(light: StaticColor.orange._7, dark: StaticColor.orangeDark._7)
        public static let _8 = Color(light: StaticColor.orange._8, dark: StaticColor.orangeDark._8)
        public static let _9 = Color(light: StaticColor.orange._9, dark: StaticColor.orangeDark._9)
        public static let _10 = Color(light: StaticColor.orange._10, dark: StaticColor.orangeDark._10)
        public static let _11 = Color(light: StaticColor.orange._11, dark: StaticColor.orangeDark._11)
        public static let _12 = Color(light: StaticColor.orange._12, dark: StaticColor.orangeDark._12)
        public static let _1Alpha = Color(light: StaticColor.orangeAlpha._1, dark: StaticColor.orangeDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.orangeAlpha._2, dark: StaticColor.orangeDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.orangeAlpha._3, dark: StaticColor.orangeDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.orangeAlpha._4, dark: StaticColor.orangeDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.orangeAlpha._5, dark: StaticColor.orangeDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.orangeAlpha._6, dark: StaticColor.orangeDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.orangeAlpha._7, dark: StaticColor.orangeDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.orangeAlpha._8, dark: StaticColor.orangeDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.orangeAlpha._9, dark: StaticColor.orangeDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.orangeAlpha._10, dark: StaticColor.orangeDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.orangeAlpha._11, dark: StaticColor.orangeDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.orangeAlpha._12, dark: StaticColor.orangeDarkAlpha._12)
    }
    public struct pink: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.pink._1, dark: StaticColor.pinkDark._1)
        public static let _2 = Color(light: StaticColor.pink._2, dark: StaticColor.pinkDark._2)
        public static let _3 = Color(light: StaticColor.pink._3, dark: StaticColor.pinkDark._3)
        public static let _4 = Color(light: StaticColor.pink._4, dark: StaticColor.pinkDark._4)
        public static let _5 = Color(light: StaticColor.pink._5, dark: StaticColor.pinkDark._5)
        public static let _6 = Color(light: StaticColor.pink._6, dark: StaticColor.pinkDark._6)
        public static let _7 = Color(light: StaticColor.pink._7, dark: StaticColor.pinkDark._7)
        public static let _8 = Color(light: StaticColor.pink._8, dark: StaticColor.pinkDark._8)
        public static let _9 = Color(light: StaticColor.pink._9, dark: StaticColor.pinkDark._9)
        public static let _10 = Color(light: StaticColor.pink._10, dark: StaticColor.pinkDark._10)
        public static let _11 = Color(light: StaticColor.pink._11, dark: StaticColor.pinkDark._11)
        public static let _12 = Color(light: StaticColor.pink._12, dark: StaticColor.pinkDark._12)
        public static let _1Alpha = Color(light: StaticColor.pinkAlpha._1, dark: StaticColor.pinkDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.pinkAlpha._2, dark: StaticColor.pinkDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.pinkAlpha._3, dark: StaticColor.pinkDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.pinkAlpha._4, dark: StaticColor.pinkDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.pinkAlpha._5, dark: StaticColor.pinkDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.pinkAlpha._6, dark: StaticColor.pinkDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.pinkAlpha._7, dark: StaticColor.pinkDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.pinkAlpha._8, dark: StaticColor.pinkDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.pinkAlpha._9, dark: StaticColor.pinkDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.pinkAlpha._10, dark: StaticColor.pinkDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.pinkAlpha._11, dark: StaticColor.pinkDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.pinkAlpha._12, dark: StaticColor.pinkDarkAlpha._12)
    }
    public struct plum: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.plum._1, dark: StaticColor.plumDark._1)
        public static let _2 = Color(light: StaticColor.plum._2, dark: StaticColor.plumDark._2)
        public static let _3 = Color(light: StaticColor.plum._3, dark: StaticColor.plumDark._3)
        public static let _4 = Color(light: StaticColor.plum._4, dark: StaticColor.plumDark._4)
        public static let _5 = Color(light: StaticColor.plum._5, dark: StaticColor.plumDark._5)
        public static let _6 = Color(light: StaticColor.plum._6, dark: StaticColor.plumDark._6)
        public static let _7 = Color(light: StaticColor.plum._7, dark: StaticColor.plumDark._7)
        public static let _8 = Color(light: StaticColor.plum._8, dark: StaticColor.plumDark._8)
        public static let _9 = Color(light: StaticColor.plum._9, dark: StaticColor.plumDark._9)
        public static let _10 = Color(light: StaticColor.plum._10, dark: StaticColor.plumDark._10)
        public static let _11 = Color(light: StaticColor.plum._11, dark: StaticColor.plumDark._11)
        public static let _12 = Color(light: StaticColor.plum._12, dark: StaticColor.plumDark._12)
        public static let _1Alpha = Color(light: StaticColor.plumAlpha._1, dark: StaticColor.plumDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.plumAlpha._2, dark: StaticColor.plumDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.plumAlpha._3, dark: StaticColor.plumDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.plumAlpha._4, dark: StaticColor.plumDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.plumAlpha._5, dark: StaticColor.plumDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.plumAlpha._6, dark: StaticColor.plumDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.plumAlpha._7, dark: StaticColor.plumDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.plumAlpha._8, dark: StaticColor.plumDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.plumAlpha._9, dark: StaticColor.plumDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.plumAlpha._10, dark: StaticColor.plumDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.plumAlpha._11, dark: StaticColor.plumDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.plumAlpha._12, dark: StaticColor.plumDarkAlpha._12)
    }
    public struct purple: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.purple._1, dark: StaticColor.purpleDark._1)
        public static let _2 = Color(light: StaticColor.purple._2, dark: StaticColor.purpleDark._2)
        public static let _3 = Color(light: StaticColor.purple._3, dark: StaticColor.purpleDark._3)
        public static let _4 = Color(light: StaticColor.purple._4, dark: StaticColor.purpleDark._4)
        public static let _5 = Color(light: StaticColor.purple._5, dark: StaticColor.purpleDark._5)
        public static let _6 = Color(light: StaticColor.purple._6, dark: StaticColor.purpleDark._6)
        public static let _7 = Color(light: StaticColor.purple._7, dark: StaticColor.purpleDark._7)
        public static let _8 = Color(light: StaticColor.purple._8, dark: StaticColor.purpleDark._8)
        public static let _9 = Color(light: StaticColor.purple._9, dark: StaticColor.purpleDark._9)
        public static let _10 = Color(light: StaticColor.purple._10, dark: StaticColor.purpleDark._10)
        public static let _11 = Color(light: StaticColor.purple._11, dark: StaticColor.purpleDark._11)
        public static let _12 = Color(light: StaticColor.purple._12, dark: StaticColor.purpleDark._12)
        public static let _1Alpha = Color(light: StaticColor.purpleAlpha._1, dark: StaticColor.purpleDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.purpleAlpha._2, dark: StaticColor.purpleDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.purpleAlpha._3, dark: StaticColor.purpleDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.purpleAlpha._4, dark: StaticColor.purpleDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.purpleAlpha._5, dark: StaticColor.purpleDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.purpleAlpha._6, dark: StaticColor.purpleDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.purpleAlpha._7, dark: StaticColor.purpleDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.purpleAlpha._8, dark: StaticColor.purpleDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.purpleAlpha._9, dark: StaticColor.purpleDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.purpleAlpha._10, dark: StaticColor.purpleDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.purpleAlpha._11, dark: StaticColor.purpleDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.purpleAlpha._12, dark: StaticColor.purpleDarkAlpha._12)
    }
    public struct red: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.red._1, dark: StaticColor.redDark._1)
        public static let _2 = Color(light: StaticColor.red._2, dark: StaticColor.redDark._2)
        public static let _3 = Color(light: StaticColor.red._3, dark: StaticColor.redDark._3)
        public static let _4 = Color(light: StaticColor.red._4, dark: StaticColor.redDark._4)
        public static let _5 = Color(light: StaticColor.red._5, dark: StaticColor.redDark._5)
        public static let _6 = Color(light: StaticColor.red._6, dark: StaticColor.redDark._6)
        public static let _7 = Color(light: StaticColor.red._7, dark: StaticColor.redDark._7)
        public static let _8 = Color(light: StaticColor.red._8, dark: StaticColor.redDark._8)
        public static let _9 = Color(light: StaticColor.red._9, dark: StaticColor.redDark._9)
        public static let _10 = Color(light: StaticColor.red._10, dark: StaticColor.redDark._10)
        public static let _11 = Color(light: StaticColor.red._11, dark: StaticColor.redDark._11)
        public static let _12 = Color(light: StaticColor.red._12, dark: StaticColor.redDark._12)
        public static let _1Alpha = Color(light: StaticColor.redAlpha._1, dark: StaticColor.redDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.redAlpha._2, dark: StaticColor.redDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.redAlpha._3, dark: StaticColor.redDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.redAlpha._4, dark: StaticColor.redDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.redAlpha._5, dark: StaticColor.redDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.redAlpha._6, dark: StaticColor.redDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.redAlpha._7, dark: StaticColor.redDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.redAlpha._8, dark: StaticColor.redDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.redAlpha._9, dark: StaticColor.redDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.redAlpha._10, dark: StaticColor.redDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.redAlpha._11, dark: StaticColor.redDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.redAlpha._12, dark: StaticColor.redDarkAlpha._12)
    }
    public struct ruby: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.ruby._1, dark: StaticColor.rubyDark._1)
        public static let _2 = Color(light: StaticColor.ruby._2, dark: StaticColor.rubyDark._2)
        public static let _3 = Color(light: StaticColor.ruby._3, dark: StaticColor.rubyDark._3)
        public static let _4 = Color(light: StaticColor.ruby._4, dark: StaticColor.rubyDark._4)
        public static let _5 = Color(light: StaticColor.ruby._5, dark: StaticColor.rubyDark._5)
        public static let _6 = Color(light: StaticColor.ruby._6, dark: StaticColor.rubyDark._6)
        public static let _7 = Color(light: StaticColor.ruby._7, dark: StaticColor.rubyDark._7)
        public static let _8 = Color(light: StaticColor.ruby._8, dark: StaticColor.rubyDark._8)
        public static let _9 = Color(light: StaticColor.ruby._9, dark: StaticColor.rubyDark._9)
        public static let _10 = Color(light: StaticColor.ruby._10, dark: StaticColor.rubyDark._10)
        public static let _11 = Color(light: StaticColor.ruby._11, dark: StaticColor.rubyDark._11)
        public static let _12 = Color(light: StaticColor.ruby._12, dark: StaticColor.rubyDark._12)
        public static let _1Alpha = Color(light: StaticColor.rubyAlpha._1, dark: StaticColor.rubyDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.rubyAlpha._2, dark: StaticColor.rubyDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.rubyAlpha._3, dark: StaticColor.rubyDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.rubyAlpha._4, dark: StaticColor.rubyDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.rubyAlpha._5, dark: StaticColor.rubyDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.rubyAlpha._6, dark: StaticColor.rubyDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.rubyAlpha._7, dark: StaticColor.rubyDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.rubyAlpha._8, dark: StaticColor.rubyDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.rubyAlpha._9, dark: StaticColor.rubyDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.rubyAlpha._10, dark: StaticColor.rubyDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.rubyAlpha._11, dark: StaticColor.rubyDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.rubyAlpha._12, dark: StaticColor.rubyDarkAlpha._12)
    }
    public struct sage: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.sage._1, dark: StaticColor.sageDark._1)
        public static let _2 = Color(light: StaticColor.sage._2, dark: StaticColor.sageDark._2)
        public static let _3 = Color(light: StaticColor.sage._3, dark: StaticColor.sageDark._3)
        public static let _4 = Color(light: StaticColor.sage._4, dark: StaticColor.sageDark._4)
        public static let _5 = Color(light: StaticColor.sage._5, dark: StaticColor.sageDark._5)
        public static let _6 = Color(light: StaticColor.sage._6, dark: StaticColor.sageDark._6)
        public static let _7 = Color(light: StaticColor.sage._7, dark: StaticColor.sageDark._7)
        public static let _8 = Color(light: StaticColor.sage._8, dark: StaticColor.sageDark._8)
        public static let _9 = Color(light: StaticColor.sage._9, dark: StaticColor.sageDark._9)
        public static let _10 = Color(light: StaticColor.sage._10, dark: StaticColor.sageDark._10)
        public static let _11 = Color(light: StaticColor.sage._11, dark: StaticColor.sageDark._11)
        public static let _12 = Color(light: StaticColor.sage._12, dark: StaticColor.sageDark._12)
        public static let _1Alpha = Color(light: StaticColor.sageAlpha._1, dark: StaticColor.sageDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.sageAlpha._2, dark: StaticColor.sageDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.sageAlpha._3, dark: StaticColor.sageDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.sageAlpha._4, dark: StaticColor.sageDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.sageAlpha._5, dark: StaticColor.sageDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.sageAlpha._6, dark: StaticColor.sageDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.sageAlpha._7, dark: StaticColor.sageDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.sageAlpha._8, dark: StaticColor.sageDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.sageAlpha._9, dark: StaticColor.sageDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.sageAlpha._10, dark: StaticColor.sageDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.sageAlpha._11, dark: StaticColor.sageDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.sageAlpha._12, dark: StaticColor.sageDarkAlpha._12)
    }
    public struct sand: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.sand._1, dark: StaticColor.sandDark._1)
        public static let _2 = Color(light: StaticColor.sand._2, dark: StaticColor.sandDark._2)
        public static let _3 = Color(light: StaticColor.sand._3, dark: StaticColor.sandDark._3)
        public static let _4 = Color(light: StaticColor.sand._4, dark: StaticColor.sandDark._4)
        public static let _5 = Color(light: StaticColor.sand._5, dark: StaticColor.sandDark._5)
        public static let _6 = Color(light: StaticColor.sand._6, dark: StaticColor.sandDark._6)
        public static let _7 = Color(light: StaticColor.sand._7, dark: StaticColor.sandDark._7)
        public static let _8 = Color(light: StaticColor.sand._8, dark: StaticColor.sandDark._8)
        public static let _9 = Color(light: StaticColor.sand._9, dark: StaticColor.sandDark._9)
        public static let _10 = Color(light: StaticColor.sand._10, dark: StaticColor.sandDark._10)
        public static let _11 = Color(light: StaticColor.sand._11, dark: StaticColor.sandDark._11)
        public static let _12 = Color(light: StaticColor.sand._12, dark: StaticColor.sandDark._12)
        public static let _1Alpha = Color(light: StaticColor.sandAlpha._1, dark: StaticColor.sandDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.sandAlpha._2, dark: StaticColor.sandDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.sandAlpha._3, dark: StaticColor.sandDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.sandAlpha._4, dark: StaticColor.sandDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.sandAlpha._5, dark: StaticColor.sandDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.sandAlpha._6, dark: StaticColor.sandDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.sandAlpha._7, dark: StaticColor.sandDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.sandAlpha._8, dark: StaticColor.sandDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.sandAlpha._9, dark: StaticColor.sandDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.sandAlpha._10, dark: StaticColor.sandDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.sandAlpha._11, dark: StaticColor.sandDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.sandAlpha._12, dark: StaticColor.sandDarkAlpha._12)
    }
    public struct sky: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.sky._1, dark: StaticColor.skyDark._1)
        public static let _2 = Color(light: StaticColor.sky._2, dark: StaticColor.skyDark._2)
        public static let _3 = Color(light: StaticColor.sky._3, dark: StaticColor.skyDark._3)
        public static let _4 = Color(light: StaticColor.sky._4, dark: StaticColor.skyDark._4)
        public static let _5 = Color(light: StaticColor.sky._5, dark: StaticColor.skyDark._5)
        public static let _6 = Color(light: StaticColor.sky._6, dark: StaticColor.skyDark._6)
        public static let _7 = Color(light: StaticColor.sky._7, dark: StaticColor.skyDark._7)
        public static let _8 = Color(light: StaticColor.sky._8, dark: StaticColor.skyDark._8)
        public static let _9 = Color(light: StaticColor.sky._9, dark: StaticColor.skyDark._9)
        public static let _10 = Color(light: StaticColor.sky._10, dark: StaticColor.skyDark._10)
        public static let _11 = Color(light: StaticColor.sky._11, dark: StaticColor.skyDark._11)
        public static let _12 = Color(light: StaticColor.sky._12, dark: StaticColor.skyDark._12)
        public static let _1Alpha = Color(light: StaticColor.skyAlpha._1, dark: StaticColor.skyDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.skyAlpha._2, dark: StaticColor.skyDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.skyAlpha._3, dark: StaticColor.skyDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.skyAlpha._4, dark: StaticColor.skyDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.skyAlpha._5, dark: StaticColor.skyDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.skyAlpha._6, dark: StaticColor.skyDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.skyAlpha._7, dark: StaticColor.skyDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.skyAlpha._8, dark: StaticColor.skyDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.skyAlpha._9, dark: StaticColor.skyDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.skyAlpha._10, dark: StaticColor.skyDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.skyAlpha._11, dark: StaticColor.skyDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.skyAlpha._12, dark: StaticColor.skyDarkAlpha._12)
    }
    public struct slate: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.slate._1, dark: StaticColor.slateDark._1)
        public static let _2 = Color(light: StaticColor.slate._2, dark: StaticColor.slateDark._2)
        public static let _3 = Color(light: StaticColor.slate._3, dark: StaticColor.slateDark._3)
        public static let _4 = Color(light: StaticColor.slate._4, dark: StaticColor.slateDark._4)
        public static let _5 = Color(light: StaticColor.slate._5, dark: StaticColor.slateDark._5)
        public static let _6 = Color(light: StaticColor.slate._6, dark: StaticColor.slateDark._6)
        public static let _7 = Color(light: StaticColor.slate._7, dark: StaticColor.slateDark._7)
        public static let _8 = Color(light: StaticColor.slate._8, dark: StaticColor.slateDark._8)
        public static let _9 = Color(light: StaticColor.slate._9, dark: StaticColor.slateDark._9)
        public static let _10 = Color(light: StaticColor.slate._10, dark: StaticColor.slateDark._10)
        public static let _11 = Color(light: StaticColor.slate._11, dark: StaticColor.slateDark._11)
        public static let _12 = Color(light: StaticColor.slate._12, dark: StaticColor.slateDark._12)
        public static let _1Alpha = Color(light: StaticColor.slateAlpha._1, dark: StaticColor.slateDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.slateAlpha._2, dark: StaticColor.slateDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.slateAlpha._3, dark: StaticColor.slateDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.slateAlpha._4, dark: StaticColor.slateDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.slateAlpha._5, dark: StaticColor.slateDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.slateAlpha._6, dark: StaticColor.slateDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.slateAlpha._7, dark: StaticColor.slateDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.slateAlpha._8, dark: StaticColor.slateDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.slateAlpha._9, dark: StaticColor.slateDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.slateAlpha._10, dark: StaticColor.slateDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.slateAlpha._11, dark: StaticColor.slateDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.slateAlpha._12, dark: StaticColor.slateDarkAlpha._12)
    }
    public struct teal: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.teal._1, dark: StaticColor.tealDark._1)
        public static let _2 = Color(light: StaticColor.teal._2, dark: StaticColor.tealDark._2)
        public static let _3 = Color(light: StaticColor.teal._3, dark: StaticColor.tealDark._3)
        public static let _4 = Color(light: StaticColor.teal._4, dark: StaticColor.tealDark._4)
        public static let _5 = Color(light: StaticColor.teal._5, dark: StaticColor.tealDark._5)
        public static let _6 = Color(light: StaticColor.teal._6, dark: StaticColor.tealDark._6)
        public static let _7 = Color(light: StaticColor.teal._7, dark: StaticColor.tealDark._7)
        public static let _8 = Color(light: StaticColor.teal._8, dark: StaticColor.tealDark._8)
        public static let _9 = Color(light: StaticColor.teal._9, dark: StaticColor.tealDark._9)
        public static let _10 = Color(light: StaticColor.teal._10, dark: StaticColor.tealDark._10)
        public static let _11 = Color(light: StaticColor.teal._11, dark: StaticColor.tealDark._11)
        public static let _12 = Color(light: StaticColor.teal._12, dark: StaticColor.tealDark._12)
        public static let _1Alpha = Color(light: StaticColor.tealAlpha._1, dark: StaticColor.tealDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.tealAlpha._2, dark: StaticColor.tealDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.tealAlpha._3, dark: StaticColor.tealDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.tealAlpha._4, dark: StaticColor.tealDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.tealAlpha._5, dark: StaticColor.tealDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.tealAlpha._6, dark: StaticColor.tealDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.tealAlpha._7, dark: StaticColor.tealDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.tealAlpha._8, dark: StaticColor.tealDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.tealAlpha._9, dark: StaticColor.tealDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.tealAlpha._10, dark: StaticColor.tealDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.tealAlpha._11, dark: StaticColor.tealDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.tealAlpha._12, dark: StaticColor.tealDarkAlpha._12)
    }
    public struct tomato: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.tomato._1, dark: StaticColor.tomatoDark._1)
        public static let _2 = Color(light: StaticColor.tomato._2, dark: StaticColor.tomatoDark._2)
        public static let _3 = Color(light: StaticColor.tomato._3, dark: StaticColor.tomatoDark._3)
        public static let _4 = Color(light: StaticColor.tomato._4, dark: StaticColor.tomatoDark._4)
        public static let _5 = Color(light: StaticColor.tomato._5, dark: StaticColor.tomatoDark._5)
        public static let _6 = Color(light: StaticColor.tomato._6, dark: StaticColor.tomatoDark._6)
        public static let _7 = Color(light: StaticColor.tomato._7, dark: StaticColor.tomatoDark._7)
        public static let _8 = Color(light: StaticColor.tomato._8, dark: StaticColor.tomatoDark._8)
        public static let _9 = Color(light: StaticColor.tomato._9, dark: StaticColor.tomatoDark._9)
        public static let _10 = Color(light: StaticColor.tomato._10, dark: StaticColor.tomatoDark._10)
        public static let _11 = Color(light: StaticColor.tomato._11, dark: StaticColor.tomatoDark._11)
        public static let _12 = Color(light: StaticColor.tomato._12, dark: StaticColor.tomatoDark._12)
        public static let _1Alpha = Color(light: StaticColor.tomatoAlpha._1, dark: StaticColor.tomatoDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.tomatoAlpha._2, dark: StaticColor.tomatoDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.tomatoAlpha._3, dark: StaticColor.tomatoDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.tomatoAlpha._4, dark: StaticColor.tomatoDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.tomatoAlpha._5, dark: StaticColor.tomatoDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.tomatoAlpha._6, dark: StaticColor.tomatoDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.tomatoAlpha._7, dark: StaticColor.tomatoDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.tomatoAlpha._8, dark: StaticColor.tomatoDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.tomatoAlpha._9, dark: StaticColor.tomatoDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.tomatoAlpha._10, dark: StaticColor.tomatoDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.tomatoAlpha._11, dark: StaticColor.tomatoDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.tomatoAlpha._12, dark: StaticColor.tomatoDarkAlpha._12)
    }
    public struct violet: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.violet._1, dark: StaticColor.violetDark._1)
        public static let _2 = Color(light: StaticColor.violet._2, dark: StaticColor.violetDark._2)
        public static let _3 = Color(light: StaticColor.violet._3, dark: StaticColor.violetDark._3)
        public static let _4 = Color(light: StaticColor.violet._4, dark: StaticColor.violetDark._4)
        public static let _5 = Color(light: StaticColor.violet._5, dark: StaticColor.violetDark._5)
        public static let _6 = Color(light: StaticColor.violet._6, dark: StaticColor.violetDark._6)
        public static let _7 = Color(light: StaticColor.violet._7, dark: StaticColor.violetDark._7)
        public static let _8 = Color(light: StaticColor.violet._8, dark: StaticColor.violetDark._8)
        public static let _9 = Color(light: StaticColor.violet._9, dark: StaticColor.violetDark._9)
        public static let _10 = Color(light: StaticColor.violet._10, dark: StaticColor.violetDark._10)
        public static let _11 = Color(light: StaticColor.violet._11, dark: StaticColor.violetDark._11)
        public static let _12 = Color(light: StaticColor.violet._12, dark: StaticColor.violetDark._12)
        public static let _1Alpha = Color(light: StaticColor.violetAlpha._1, dark: StaticColor.violetDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.violetAlpha._2, dark: StaticColor.violetDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.violetAlpha._3, dark: StaticColor.violetDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.violetAlpha._4, dark: StaticColor.violetDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.violetAlpha._5, dark: StaticColor.violetDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.violetAlpha._6, dark: StaticColor.violetDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.violetAlpha._7, dark: StaticColor.violetDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.violetAlpha._8, dark: StaticColor.violetDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.violetAlpha._9, dark: StaticColor.violetDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.violetAlpha._10, dark: StaticColor.violetDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.violetAlpha._11, dark: StaticColor.violetDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.violetAlpha._12, dark: StaticColor.violetDarkAlpha._12)
    }
    public struct whiteAlpha: PaletteColor {
        public init() {}
        public static let _1 = StaticColor.whiteAlpha._1
        public static let _2 = StaticColor.whiteAlpha._2
        public static let _3 = StaticColor.whiteAlpha._3
        public static let _4 = StaticColor.whiteAlpha._4
        public static let _5 = StaticColor.whiteAlpha._5
        public static let _6 = StaticColor.whiteAlpha._6
        public static let _7 = StaticColor.whiteAlpha._7
        public static let _8 = StaticColor.whiteAlpha._8
        public static let _9 = StaticColor.whiteAlpha._9
        public static let _10 = StaticColor.whiteAlpha._10
        public static let _11 = StaticColor.whiteAlpha._11
        public static let _12 = StaticColor.whiteAlpha._12
        public static let _1Alpha = StaticColor.whiteAlpha._1
        public static let _2Alpha = StaticColor.whiteAlpha._2
        public static let _3Alpha = StaticColor.whiteAlpha._3
        public static let _4Alpha = StaticColor.whiteAlpha._4
        public static let _5Alpha = StaticColor.whiteAlpha._5
        public static let _6Alpha = StaticColor.whiteAlpha._6
        public static let _7Alpha = StaticColor.whiteAlpha._7
        public static let _8Alpha = StaticColor.whiteAlpha._8
        public static let _9Alpha = StaticColor.whiteAlpha._9
        public static let _10Alpha = StaticColor.whiteAlpha._10
        public static let _11Alpha = StaticColor.whiteAlpha._11
        public static let _12Alpha = StaticColor.whiteAlpha._12
    }
    public struct yellow: PaletteColor {
        public init() {}
        public static let _1 = Color(light: StaticColor.yellow._1, dark: StaticColor.yellowDark._1)
        public static let _2 = Color(light: StaticColor.yellow._2, dark: StaticColor.yellowDark._2)
        public static let _3 = Color(light: StaticColor.yellow._3, dark: StaticColor.yellowDark._3)
        public static let _4 = Color(light: StaticColor.yellow._4, dark: StaticColor.yellowDark._4)
        public static let _5 = Color(light: StaticColor.yellow._5, dark: StaticColor.yellowDark._5)
        public static let _6 = Color(light: StaticColor.yellow._6, dark: StaticColor.yellowDark._6)
        public static let _7 = Color(light: StaticColor.yellow._7, dark: StaticColor.yellowDark._7)
        public static let _8 = Color(light: StaticColor.yellow._8, dark: StaticColor.yellowDark._8)
        public static let _9 = Color(light: StaticColor.yellow._9, dark: StaticColor.yellowDark._9)
        public static let _10 = Color(light: StaticColor.yellow._10, dark: StaticColor.yellowDark._10)
        public static let _11 = Color(light: StaticColor.yellow._11, dark: StaticColor.yellowDark._11)
        public static let _12 = Color(light: StaticColor.yellow._12, dark: StaticColor.yellowDark._12)
        public static let _1Alpha = Color(light: StaticColor.yellowAlpha._1, dark: StaticColor.yellowDarkAlpha._1)
        public static let _2Alpha = Color(light: StaticColor.yellowAlpha._2, dark: StaticColor.yellowDarkAlpha._2)
        public static let _3Alpha = Color(light: StaticColor.yellowAlpha._3, dark: StaticColor.yellowDarkAlpha._3)
        public static let _4Alpha = Color(light: StaticColor.yellowAlpha._4, dark: StaticColor.yellowDarkAlpha._4)
        public static let _5Alpha = Color(light: StaticColor.yellowAlpha._5, dark: StaticColor.yellowDarkAlpha._5)
        public static let _6Alpha = Color(light: StaticColor.yellowAlpha._6, dark: StaticColor.yellowDarkAlpha._6)
        public static let _7Alpha = Color(light: StaticColor.yellowAlpha._7, dark: StaticColor.yellowDarkAlpha._7)
        public static let _8Alpha = Color(light: StaticColor.yellowAlpha._8, dark: StaticColor.yellowDarkAlpha._8)
        public static let _9Alpha = Color(light: StaticColor.yellowAlpha._9, dark: StaticColor.yellowDarkAlpha._9)
        public static let _10Alpha = Color(light: StaticColor.yellowAlpha._10, dark: StaticColor.yellowDarkAlpha._10)
        public static let _11Alpha = Color(light: StaticColor.yellowAlpha._11, dark: StaticColor.yellowDarkAlpha._11)
        public static let _12Alpha = Color(light: StaticColor.yellowAlpha._12, dark: StaticColor.yellowDarkAlpha._12)
    }
}
